version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: airflow_redis
    restart: always
    ports:
      - "6379:6379"

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow_webserver.
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow:/opt/airflow/dags
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_dag:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
      - ./web_scraping:/opt/airflow/web_scraping
      - ./load_to_postgresql:/opt/airflow/load_to_postgresql
      - ./load_to_redshift:/opt/airflow/load_to_redshift
      - ./load_to_s3:/opt/airflow/load_to_s3
      - ./transformation:/opt/airflow/transformation
      - ./data_stage:/opt/airflow/data_stage
      - ./.env:/opt/airflow/.env
      - ./real_estate:/opt/airflow/real_estate
    entrypoint: 
      - "bash"
      - "-c"
      - |
        chmod -R 777 /opt/airflow/dags /opt/airflow/transformation
        chown -R airflow:airflow /opt/airflow/dags /opt/airflow/transformation
        pip install -r /requirements.txt
        airflow db upgrade
        airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email dinhvietquyen1803@gmail.com
        airflow webserver

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow_scheduler.
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow:/opt/airflow/dags
    volumes:
      - ./airflow_dag:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./web_scraping:/opt/airflow/web_scraping
      - ./load_to_postgresql:/opt/airflow/load_to_postgresql
      - ./load_to_redshift:/opt/airflow/load_to_redshift
      - ./load_to_s3:/opt/airflow/load_to_s3
      - ./transformation:/opt/airflow/transformation
      - ./data_stage:/opt/airflow/data_stage
      - ./.env:/opt/airflow/.env
      - ./real_estate:/opt/airflow/real_estate
      - ./requirements.txt:/requirements.txt
    entrypoint: 
      - "bash"
      - "-c"
      - |
        chmod -R 777 /opt/airflow/dags /opt/airflow/transformation
        chown -R airflow:airflow /opt/airflow/dags /opt/airflow/transformation
        pip install -r /requirements.txt  
        airflow scheduler

  airflow-worker:
    image: apache/airflow:latest
    container_name: airflow_worker
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow:/opt/airflow/dags
    volumes:
      - ./airflow_dag:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./web_scraping:/opt/airflow/web_scraping
      - ./load_to_postgresql:/opt/airflow/load_to_postgresql
      - ./load_to_redshift:/opt/airflow/load_to_redshift
      - ./load_to_s3:/opt/airflow/load_to_s3
      - ./transformation:/opt/airflow/transformation
      - ./requirements.txt:/requirements.txt
      - ./data_stage:/opt/airflow/data_stage
      - ./.env:/opt/airflow/.env
      - ./real_estate:/opt/airflow/real_estate
    entrypoint: 
      - "bash"
      - "-c"
      - |
        chmod -R 777 /opt/airflow/dags /opt/airflow/transformation
        chown -R airflow:airflow /opt/airflow/dags /opt/airflow/transformation
        pip install -r /requirements.txt
        airflow celery worker

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  airflow_logs:
  pgadmin_data: